fix: [filedialog] add file dialog feature
deepin-community/gtkplus3.0 pull request #1
Opened 2023-06-19 09:46 UTC by GongHeng2017

copy the patch from gerrit stroehouse of develop/snipe branch.

2023-06-19 09:55 UTC, hudeng-go requested changes

2023-06-19 09:55 UTC, hudeng-go commented on debian/changelog
> +gtk+3.0 (3.24.30.6-deepin6) unstable; urgency=medium
版本号是不是要调整一下，3.24.30-deepin6就行，目前的版本号规则是上游版本号某某+deepin(1...n)，例如本次gtk的正常应该是3.24.30-3deepin6，但是鉴于历史版本高于这个版本，可能会降级，因此可以折中使用该方案。

2023-06-19 09:56 UTC, hudeng-go commented
/cc @Zeno-sole @UTsweetyfish @Rabenda

2023-06-19 10:12 UTC, GongHeng2017 commented on debian/changelog
> +gtk+3.0 (3.24.30.6-deepin6) unstable; urgency=medium
done

2023-06-19 10:14 UTC, hudeng-go commented
/approve need lgtm by another reviewer.

2023-06-20 02:50 UTC, hudeng-go commented
/lgtm

2023-06-20 02:51 UTC, merged